//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrift_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Images = new HashSet<Image>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Wishlists = new HashSet<Wishlist>();
        }

        [Display(Name = "Product ID")]
        public int ProductID { get; set; }

        [Display(Name = "Brand ID")]
        [Required(ErrorMessage = "Brand ID is not empty")]
        public int BrandID { get; set; }

        [Display(Name = "Category ID")]
        [Required(ErrorMessage = "Category ID is not empty")]
        public int CategoryID { get; set; }

        [Display(Name = "Product's Name")]
        [Required(ErrorMessage = "Product's Name is not empty")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Description is not empty")]
        public string Description { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Price is not empty")]
        public decimal Price { get; set; }

        [Range(1,int.MaxValue , ErrorMessage = "Quantity must have greater than 1 ")]
        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Quantity is not empty")]      
        public int Quantity { get; set; }

        [Range(0,100,ErrorMessage ="Discount is out of Range(0 - 100)")]
        [Display(Name = "Discount")]
        public int Discount { get; set; }

        [Display(Name = "Image")]
        public string Image { get; set; }

        [Display(Name = "Created Date")]
        [Required(ErrorMessage = "Created Date is not empty")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime CreatedDate { get; set; }

        [Display(Name = "Status")]
        public bool Status { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
